### ISSUE TITLE
71347448 Running on a Secondary (Stephen)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeUKRegProductIssues#949]
Issue reported by **steveroland** at 2017-04-05 18:44:08 UTC
Time: 2017-04-05T18:40:45+00:00
Session ID: 8d44599b19bcad2d13bf284dd3ab282b
Problem Page URL: [/manage_resources/new](/manage_resources/new)
Previous Page URL: [https://www.freereg.org.uk/cms/refinery/login](https://www.freereg.org.uk/cms/refinery/login)
Reported Issue:
Having closed a Chrome browser with FR logged in, several hours later I open a new Chrome browser and get the message; "You appear to be running on a secondary. Please log in again". However, I cannot logout or login as it then says "Too many redirects". I tried clearing cookies but no joy. The only way is to use a different browser.
http://www13.freereg.org.uk/uploads/feedback/screenshot/58e53af8f493fd077f503d33/Capture.jpg    

![Screenshot](http://www.freereg.org.uk/uploads/feedback/screenshot/58e53af8f493fd077f503d33/Capture.jpg)

**Comment by ghost** [comment]
![capture](https://cloud.githubusercontent.com/assets/20557838/24768095/44ef7b08-1af9-11e7-84f4-c0ad4502f613.jpg)

**Comment by edickens** [comment]
I also noted when using Chrome for this week's conference calls that there does not seem to be a way to log out.  I don't think that closing the browser or leaving the call logs out.  So is it a Chrome problem?

**Comment by Sherlock21** [comment]
I have had this same message several times this week - say Tuesday onwards - and it was not corrected by deleting All my caches etc.

I am on Safari on an iMac.

Just took half an hour off, did something else then tried again.
It was accompanied by everything taking very long times to respond.

I have not logged ontoFR Prod today yet.

**Comment by Captainkirkdawson** [comment]
To remove cookies in chrome. Select secure; select www.freereg.org.uk then cookies and remove
![cookieremoval](https://cloud.githubusercontent.com/assets/2874694/24770879/bbc5f76a-1ac8-11e7-9b79-198028269ec6.JPG)
The selection of www.freereg.org.uk is vital as you may have other similar looking urls for test3 and freereg.org.uk
Similar for firefox

**Comment by Captainkirkdawson** [comment]
Is any further action on this required?

**Comment by Captainkirkdawson** [comment]
Need to review if better/message action is possible to avoid member difficulties

**Comment by SteveBiggs** [comment]
I am still experiencing this from time to time. It could be related to the performance problems on the site. Clearing cookies does not resolve. I have to keep changing browsers until one lets me login.

**Comment by PatReynolds** [comment]
No longer appears to be an issue.
